### PR TITLE
PR Xolos RMZ to Verse

### PR DESCRIPTION
**Pull request by Gutiman18**
### Token Details
- **Token symbol: RMZ**
- **Token name: Xolos **
- **Wallet address used to provide initial pool liquidity: 0x8f0DdeEA2406f327a8E9adB47aD968d87C3A6bbd**

### Checklist
- [ ] Filled out token details above
- [ ] Added token info to tokens.json
- [ ] Added token icon to /icons

### CODE REVIEW

**Comment by allisonle** [comment]
hi @Gutiman18, token icons need to be transparent circular PNGs and 64x64 ([example](https://github.com/bitcoin-portal/verse-dex-tokens/blob/trunk/icons/flexusd2x.png)). could you please update?

**Comment by Gutiman18** [comment]
Ok, Let me check

**Comment by vm06007** [comment]
please see if you can add initial liquidity on https://verse.bitcoin.com/ using provided wallet address

**Comment by Gutiman18** [comment]
Done! https://www.smartscan.cash/transaction/0x126d934f53238b453c52396eab8a003d3d2ae10d4d38670f26fc4d69a78e8ef8

**Comment by Gutiman18** [comment]
> please see if you can add initial liquidity on https://verse.bitcoin.com/ using provided wallet address

Hello, I have access Verse using provided wallet, but when  logging in I cant see my LP. Why?

**Pull request merged**
