### PR TITLE
Add SSS [SEP-20]

### PR DESCRIPTION
**Pull request by Tellbird**
### Token Details
- **Token symbol:SSS
- **Token name:SSS
- **Wallet address used to provide initial pool liquidity:0xdD1C1f8f57f7cA6bf3Bd8eE7Ea1A839277BbfcEA

### Checklist
- [x] Filled out token details above
- [x] Added token info to tokens.json
- [x] Added token icon to /icons

### CODE REVIEW

**Comment by Tellbird** [comment]
Website: https://sss.cash/
Docs: https://doc.sss.cash/
Telegram: https://t.me/ssscash
Twitter: https://twitter.com/3scash
GitHub: https://github.com/SSSCASH
Audit-reports：https://github.com/0xGuard-com/audit-reports/blob/master/SSS.CASH/SSS.CASH.pdf
Contract：0x9c106Dd7F8d3f873779696654d55e79ebC89bA7A

**Comment by vm06007** [comment]
`This branch has conflicts that must be resolved` could you please resolve conflict in this PR?

**Comment by Tellbird** [comment]
> `This branch has conflicts that must be resolved` could you please resolve conflict in this PR?

Hi, I have updated the latest tokens.json. You see if the changes meet the requirements.

**Comment by vm06007** [comment]
please see if you can add initial liquidity on https://verse.bitcoin.com/ using provided wallet address

**Comment by Tellbird** [comment]
> please see if you can add initial liquidity on https://verse.bitcoin.com/ using provided wallet address

Sorry sir, I left the wrong Wallet address used to provide initial pool liquidity, I have corrected it now, the correct address is: 0xdD1C1f8f57f7cA6bf3Bd8eE7Ea1A839277BbfcEA
Sorry again!

**Comment by vm06007** [comment]
Please check now

**Comment by Tellbird** [comment]
> Please check now


please see if you can add initial liquidity on https://verse.bitcoin.com/ using provided wallet address

Thx，I have added liquidity to the token.

**Comment by bmthint701** [comment]
hello @Tellbird we have removed your token from being tradeable as we have been notified (and can verify ourselves) that people are not able to sell.

Can you provide a justification of why this is the case? If we do not hear back from you within 48 hours we will remove SSS from the My Investments tab so you will need to manually call the contract to remove your previously provided liquidity

**Comment by Tellbird** [comment]
> hello @Tellbird we have removed your token from being tradeable as we have been notified (and can verify ourselves) that people are not able to sell.
> 
> Can you provide a justification of why this is the case? If we do not hear back from you within 48 hours we will remove SSS from the My Investments tab so you will need to manually call the contract to remove your previously provided liquidity

Of course, we explain to you clearly that algorithmic stablecoins include a tax system, so you need to increase the slippage to complete the transaction. The link is a detailed introduction to the system.
[https://doc.sss.cash/protocol/gatekeeper-system](https://doc.sss.cash/protocol/gatekeeper-system)

**Comment by Tellbird** [comment]
> hello @Tellbird we have removed your token from being tradeable as we have been notified (and can verify ourselves) that people are not able to sell.
> 
> Can you provide a justification of why this is the case? If we do not hear back from you within 48 hours we will remove SSS from the My Investments tab so you will need to manually call the contract to remove your previously provided liquidity

taxrateeng

**Pull request closed without merging**
