### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by allisonle**

### CODE REVIEW

**Comment by Meandonlyme9** [comment]
I got a email stating that u havent checked on my bitcoin s for a year and
I have 24 000 I need to with draw if I send the 62 00 fee to get them
switched over is this correct

**Review by jtxmp — APPROVED** [review]
thank you!

**Comment by ZarinDen** [comment]
"decimals": 18,
            "pairs": ["BCH"]
        },
        {
            "abbr": "MIST",
            "value": "MIST",
            "protocol": "SEP20_PROTOCOL",
            "blockchain": "BCH",
            "label": "MIST",
            "ticker": "mist",
            "explorer": "https://www.smartscan.cash/tx/",
            "token": "0x5fA664f69c2A4A3ec94FaC3cBf7049BD9CA73129",
            "decimals": 18,
            "pairs": ["BCH"]
        },
        {

**Comment by KingRobZombie-CEO** [comment]
Hello

**Comment by rawmet1989** [comment]
??

**Comment by BhinbahadurUK** [comment]
Yes

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Review by walker112171 — COMMENTED** [review]
Explain

**Comment by rawmet1989** [comment]
Tater juice I’m trying to figure out how to figure out where all my tokens and how to pull it up and all the things in the code just tell the truth it’s like gibberish to me but I’m trying to figure it out just do random things can you help


Sent from Yahoo Mail for iPhone


On Thursday, February 22, 2024, 2:52 AM, walker112171 ***@***.***> wrote:




@walker112171 commented on this pull request.

Explain

**Review by walker112171 — COMMENTED** [review]
Good

**Comment by rawmet1989** [comment]
??

**Comment by rawmet1989** [comment]
Hey 

Sent from Yahoo Mail for iPhone

**Pull request merged**
