### PR TITLE
Create devcontainer.json

### PR DESCRIPTION
**Pull request by C3mkal**
### Token Details
- **Token symbol:**
- **Token name:**
- **Project website:**
- **Wallet address used to provide initial pool liquidity:**
- **Initial amount of liquidity you intend to provide:**

### Checklist
- [ ] Filled out token details above
- [ ] Added token info to tokens.json
- [ ] Added token icon to /icons

### CODE REVIEW

**Review by Meems2020 — COMMENTED** [review]
In slowly getting the hang of stuff looks good

**Comment by ashnbill** [comment]
> ### Token Details0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d
> * **Token symbol:**.github/PULL_REQUEST_TEMPLATE.md
> * **Token name:**
> * **Project website:**0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d
> * **Wallet address used to provide initial pool liquidity:**liquidity:0x8f0DdeEA2406f327a8E9adB47aD968d87C3A6bbd
> * **Initial amount of liquidity you intend to provide:**1
> 
> ### Checklist
> * [ ]  Filled out token details above
> * [ ]  Added token info to tokens.json
> * [ ]  Added token icon to /icons

**Review by ashnbill — COMMENTED** [review]
Yes

**Review by Meems2020 — COMMENTED** [review]
Ok

**Comment by ashnbill** [comment]
Ymerge

**Comment by ashnbill** [comment]
Merge

**Review by ashnbill — COMMENTED** [review]
Approve

**Pull request closed without merging**
