### PR TITLE
Example

### PR DESCRIPTION
**Pull request by allisonle**
### Token Details
- **Token symbol:** FLEX
- **Token name:** FLEX
- **Wallet address used to provide initial pool liquidity:** `0x7fae227057989C9bC0afAeCFEf18Bc68a6e03161`

### Checklist
- [x] Filled out token details above
- [x] Added token info to tokens.json
- [x] Added token icon to /icon

### CODE REVIEW

**Comment by ponury1990** [comment]
{
        "abbr": "JOY", // token symbol
        "value": "JOY", // same as abbr
        "protocol": "SEP20_PROTOCOL",
        "blockchain": "BCH",
        "label": "JOY", // token display name
        "ticker": "joy",
        "explorer": "https://www.smartscan.cash/tx/",
        "token": "0x6732E55Ac3ECa734F54C26Bd8DF4eED52Fb79a6E", // token contract address
        "decimals": 18,
        "pairs": ["BCH", "TANGO"] // this will add JOY/BCH and JOY/TANGO to the list of liquidity pools
    }0x7Bb553caE2A0Fcd7c73cEF27120eDAc2fb3d5282

**Review by 0349998773 — COMMENTED** [review]
[]()9349998773

**Review by n6wbb6 — COMMENTED** [review]
Y

**Review by mspaansen — COMMENTED** [review]
😀

**Pull request merged**
