### PR TITLE
Add MIST

### PR DESCRIPTION
**Pull request by mainnet-pat**
### Token Details
- **Token symbol:** MIST
- **Token name:** MIST
- **Wallet address used to provide initial pool liquidity:** 0x07D4115bCDb2b709ff07d0dA11f5Da7D85C5b769

### Checklist
- [x] Filled out token details above
- [x] Added token info to tokens.json
- [x] Added token icon to /icons

### CODE REVIEW

**Comment by vm06007** [comment]
please see if you can add initial liquidity on https://verse.bitcoin.com/ using provided wallet address

**Comment by kasumi-1** [comment]
Hi @vm06007 - my apologies but a miscommunication occurred and wrong address was provided.

Can you please update to `0xd2465F41558944d6fb4628D37aB00E3070b954F9` I can provide liquidity using this. Thanks.

**Comment by vm06007** [comment]
please try now

**Comment by kasumi-1** [comment]
done, thanks

**Comment by ponury1990** [comment]
{
        "abbr": "JOY", // token symbol
        "value": "JOY", // same as abbr
        "protocol": "SEP20_PROTOCOL",
        "blockchain": "BCH",
        "label": "JOY", // token display name
        "ticker": "joy",
        "explorer": "https://www.smartscan.cash/tx/",
        "token": "0x6732E55Ac3ECa734F54C26Bd8DF4eED52Fb79a6E", // token contract address
        "decimals": 18,
        "pairs": ["BCH", "TANGO"] // this will add JOY/BCH and JOY/TANGO to the list of liquidity pools
    }

**Review by QueenMe93 — COMMENTED** [review]
I want access to my own Bitcoin

**Pull request merged**
