### PR TITLE
Adds the token Ki, from our Swap and bridge to BSC. 

### PR DESCRIPTION
**Pull request by stebansaa**
### Token Details
- **Token symbol:**
Ki
- **Token name:**
Ki 
- **Wallet address used to provide initial pool liquidity:**
We have all the funds on an LP, Will move 10BCH for Verse LP.

### Checklist
- [ x] Filled out token details above
- [x ] Added token info to tokens.json
- [x ] Added token icon to /icons

### CODE REVIEW

**Comment by bmthint701** [comment]
hello @stebansaa we need a wallet addres that will be used for funding the LP

**Comment by bmthint701** [comment]
@stebansaa following up here

**Review by Cplus360 — APPROVED** [review]
SEP20 check good

**Review by Cplus360 — COMMENTED** [review]
Any issues please update

**Pull request closed without merging**
