### PR TITLE
Merge verse 

### PR DESCRIPTION
**Pull request by ghost**
### Token Details
- **Token symbol:**
- **Token name:**
- **Project website:**
- **Wallet address used to provide initial pool liquidity:**
- **Initial amount of liquidity you intend to provide:**

### Checklist
- [x] Filled out token details above
- [x] Added token info to tokens.json
- [x] Added token icon to /icons

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
A0pprove

**Review by ghost — COMMENTED** [review]
Btc approve

**Comment by BhinbahadurUK** [comment]
UKB is the name . Note symbol is ohm sign it trademarks upside down u with
side ends folded flat.


www.ukbfindev.org



And wallet address is :

https://play.google.com/store/apps/details?id=app.fxroyalepro.com

**Review by ashnbill — COMMENTED** [review]
viewed

**Comment by csilence918** [comment]
T hanks

**Comment by csilence918** [comment]
> A0pprove

$

**Pull request closed without merging**
