### PR TITLE
added 1BCH tokens

### PR DESCRIPTION
**Pull request by 1BCHDev1**
### Token Details
- **Token symbol:** 1BCH
- **Token name:** 1BCH
- **Wallet address used to provide initial pool liquidity:** 0x8AfF534d5290efE4F429EB64eDd3082cE623fC20

### Token Details
- **Token symbol:** rBCH
- **Token name:** rBCH
- **Wallet address used to provide initial pool liquidity:** 0x8AfF534d5290efE4F429EB64eDd3082cE623fC20

### Checklist
- [x] Filled out token details above
- [x] Added token info to tokens.json
- [x] Added token icon to /icons

### CODE REVIEW

**Comment by allisonle** [comment]
Hi @1BCHDev1, your pairs are now ready to be funded by the provided wallet address on https://verse.bitcoin.com/!

**Comment by 1BCHDev1** [comment]
Please excuse teh delay, where on the page can we fund a new pair, on the pair page there seam only to be options to add liquidity to existing pairs.

**Comment by Rfhugigf** [comment]
diff --git a/config/tokens.json b/config/tokens.json
index cd794ca..1fa6458 100644
--- a/config/tokens.json
+++ b/config/tokens.json
@@ -35,6 +35,30 @@
             "token": "0x6732E55Ac3ECa734F54C26Bd8DF4eED52Fb79a6E",
             "decimals": 18,
             "pairs": ["BCH"]
+        },
+        {
+            "abbr": "1BCH",
+            "value": "1BCH",
+            "protocol": "SEP20_PROTOCOL",
+            "blockchain": "BCH",
+            "label": "1BCH",
+            "ticker": "1bch",
+            "explorer": "https://www.smartscan.cash/tx/",
+            "token": "0x77d4b6e44a53bbda9a1d156b32bb53a2d099e53d",
+            "decimals": 18,
+            "pairs": ["BCH"]
+        },
+        {
+            "abbr": "rBCH",
+            "value": "rBCH",
+            "protocol": "SEP20_PROTOCOL",
+            "blockchain": "BCH",
+            "label": "rBCH",
+            "ticker": "rbch",
+            "explorer": "https://www.smartscan.cash/tx/",
+            "token": "0xb4602588e5f1f9653b6f234206c91552e457facb",
+            "decimals": 18,
+            "pairs": ["BCH"]
         }
     ]
 }
diff --git a/icons/0x77d4b6e44a53bbda9a1d156b32bb53a2d099e53d.png b/icons/0x77d4b6e44a53bbda9a1d156b32bb53a2d099e53d.png
new file mode 100644
index 0000000..58a8f61
Binary files /dev/null and b/icons/0x77d4b6e44a53bbda9a1d156b32bb53a2d099e53d.png differ
diff --git a/icons/0xb4602588e5f1f9653b6f234206c91552e457facb.png b/icons/0xb4602588e5f1f9653b6f234206c91552e457facb.png
new file mode 100644
index 0000000..7033a31
Binary files /dev/null and b/icons/0xb4602588e5f1f9653b6f234206c91552e457facb.png differ

**Comment by CharliesAngel1** [comment]
ddurel24@gmail.com

**Pull request closed without merging**
