### PR TITLE
Add TANGO (SEP20)

### PR DESCRIPTION
**Pull request by ianblas**
### Token Details
- **Token symbol:*TANGO*
- **Token name:*TANGO*
- **Wallet address used to provide initial pool liquidity: *0x9331786bEFEC8D08335EA3aC4562bde9514520bE (Dev Wallet)*

### Checklist
- ☑ Filled out token details above
- ☑ Added token info to tokens.json
- ☑ Added token icon to /icons

### CODE REVIEW

**Review by allisonle — APPROVED** [review]

**Comment by allisonle** [comment]
Hi @ianblas , the BCH/TANGO pair is now ready to be funded by the provided wallet address on https://verse.bitcoin.com/!

**Comment by bmthint701** [comment]
hey @ianblas just wanna check in if you are having any issues, let us know :). The pair won't be visible until _you_ add liquidity

**Comment by ianblas** [comment]
Hi, i can't see the BCH/TANGO pair

**Comment by bmthint701** [comment]
oh I'm sorry about that! can you please confirm you are looking for it in the "My Investments" tab, connected with the wallet you specified as the funding wallet? 0x9331786bEFEC8D08335EA3aC4562bde9514520bE

**Comment by bmthint701** [comment]
hello @ianblas just want to follow up here :)

**Pull request merged**
